import type { Metadata } from 'next'
import {
  Noto_Sans,
  Noto_Sans_Display,
  Noto_Serif,
  Noto_Serif_Display,
} from 'next/font/google'
import './globals.scss'

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
})

const notoSansDisplay = Noto_Sans_Display({
  variable: '--font-noto-sans-display',
  subsets: ['latin'],
})

const notoSerif = Noto_Serif({
  variable: '--font-noto-serif',
  subsets: ['latin'],
})

const notoSerifDisplay = Noto_Serif_Display({
  variable: '--font-noto-serif-display',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${notoSans.variable} ${notoSansDisplay.variable} ${notoSerif.variable} ${notoSerifDisplay.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
